version: "3.7"

networks:
  app-tier:
    driver: bridge

services:
  mongodb:
    image: bitnami/mongodb:4.2.5-debian-10-r10
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/bitnami
    networks:
      - app-tier

  comparator:
    build: ./
    volumes:
      - ./:/app/
    command: [yarn, workspace, "@bet/comparator", dev]
    environment:
      - BET_TELEGRAM_BOT_TOKEN=1038969865:AAFLLkFSH5nSCQWDIXN1tniNyGcr714ugj0
      - TELEGRAM_OPPORTUNITY_CHAT_ID=-1001355004972
    networks:
      - app-tier
    depends_on:
      - mongodb

  health:
    build: ./
    volumes:
      - ./:/app/
    command: [yarn, workspace, "@bet/health", dev]
    networks:
      - app-tier
    depends_on:
      - mongodb

  # Scrapers

  scraper-marathon:
    build:
      context: ./
      args:
        INSTALL_CHROMIUM: "true"
    volumes:
      - ./:/app/
    command: [yarn, workspace, "@bet/scraper-marathon", dev]
    networks:
      - app-tier
    depends_on:
      - mongodb

  scraper-pinnacle:
    build: ./
    volumes:
      - ./:/app/
    command: [yarn, workspace, "@bet/scraper-pinnacle", dev]
    networks:
      - app-tier
    depends_on:
      - mongodb

  # scraper-1xbet:
  #   build:
  #     context: ./
  #     args:
  #       INSTALL_CHROMIUM: true
  #   volumes:
  #     - ./:/app/
  #   command: [yarn, workspace, "@bet/scraper-pinnacle", dev]
  #   networks:
  #     - app-tier
  #   depends_on:
  #     - mongodb
  #
  # End of scrapers

volumes:
  mongodb_data:
    driver: local
