version: "3.7"

# Extension fields start
# https://docs.docker.com/compose/compose-file/#extension-fields

# Volumes to share between services
x-volumes: &default-volumes
  - ./.yarn/cache:/app/.yarn/cache:ro
  - ./.yarn/plugins:/app/.yarn/plugins:ro
  - ./.yarn/releases:/app/.yarn/releases:ro
  - ./packages:/app/packages:ro
  - ./services:/app/services:ro
  - ./.pnp.js:/app/.pnp.js:ro
  - ./.yarnrc.yml:/app/.yarnrc.yml:ro
  - ./package.json:/app/package.json:ro
  - ./tsconfig.json:/app/tsconfig.json:ro
  - ./yarn.lock:/app/yarn.lock:ro

# Minimal headless chrome service configuration
x-headless-chrome: &headless-chrome
  build:
    context: ./
    args:
      INSTALL_CHROMIUM: "true"
  shm_size: 1gb
  init: true
  security_opt:
    - seccomp=docker/seccomp-chromium.json

# Extension fields end

networks:
  app-tier:
    driver: bridge

services:
  mongodb:
    image: bitnami/mongodb:4.2.5-debian-10-r10
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/bitnami
    networks:
      - app-tier

  comparator:
    build: ./
    volumes: *default-volumes
    command: [yarn, workspace, "@bet/comparator", dev]
    environment:
      - BET_TELEGRAM_BOT_TOKEN=1001253173:AAFY2ven2e7ezTjddRvmsUJRJS2ulCX-1o4
      - TELEGRAM_OPPORTUNITY_CHAT_ID=-1001475105744
      - MONGODB_CONNECTION_URI=mongodb://mongodb
    networks:
      - app-tier
    depends_on:
      - mongodb

  health:
    build: ./
    volumes: *default-volumes
    command: [yarn, workspace, "@bet/health", dev]
    environment:
      - MONGODB_CONNECTION_URI=mongodb://mongodb
    networks:
      - app-tier
    depends_on:
      - mongodb

  # Scrapers

  scraper-marathon:
    build: ./
    volumes: *default-volumes
    command: [yarn, workspace, "@bet/scraper-marathon", dev]
    environment:
      - MONGODB_CONNECTION_URI=mongodb://mongodb
    networks:
      - app-tier
    depends_on:
      - mongodb

  scraper-pinnacle:
    build: ./
    volumes: *default-volumes
    command: [yarn, workspace, "@bet/scraper-pinnacle", dev]
    environment:
      - MONGODB_CONNECTION_URI=mongodb://mongodb
    networks:
      - app-tier
    depends_on:
      - mongodb

  # scraper-1xbet:
  #   <<: *headless-chrome
  #   volumes: *default-volumes
  #   command: [yarn, workspace, "@bet/scraper-pinnacle", dev]
  #   environment:
  #     - MONGODB_CONNECTION_URI=mongodb://mongodb
  #   networks:
  #     - app-tier
  #   depends_on:
  #     - mongodb
  #
  # End of scrapers

volumes:
  mongodb_data:
    driver: local
