version: '3'

networks:
  app-tier:
    driver: bridge

services:

  mongodb:
    image: 'bitnami/mongodb:4.0'
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami'
    networks:
      - app-tier

  scrapper:
    build: ./scrapper
    volumes:
      - "./scrapper:/usr/app"
      - /usr/app/node_modules
    command: [ "npm", "run", "dev"]
    networks:
      - app-tier
    depends_on:
      - mongodb

  comparator:
    build: ./comparator
    volumes:
      - "./comparator:/usr/app"
      - /usr/app/node_modules
    command: [ "npm", "run", "dev"]
    networks:
      - app-tier
    depends_on:
      - mongodb

  health:
    build: ./health
    volumes:
      - "./health:/usr/app"
      - /usr/app/node_modules
    command: [ "npm", "run", "dev"]
    networks:
      - app-tier
    depends_on:
      - mongodb
    
volumes:
  mongodb_data:
    driver: local
