version: '3.4'

networks:
  app-tier:
    driver: bridge

services:

  mongodb:
    image: 'bitnami/mongodb:4.0'
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami'
    networks:
      - app-tier

  comparator:
    build: ./comparator
    volumes:
      - "./comparator:/usr/app"
      - /usr/app/node_modules
    command: [ "npm", "run", "dev"]
    environment:
      - BET_TELEGRAM_BOT_TOKEN=1038969865:AAFLLkFSH5nSCQWDIXN1tniNyGcr714ugj0
      - TELEGRAM_OPPORTUNITY_CHAT_ID=-445597702
    networks:
      - app-tier
    depends_on:
      - mongodb

  health:
    build: ./health
    volumes:
      - "./health:/usr/app"
      - /usr/app/node_modules
    command: [ "npm", "run", "dev"]
    networks:
      - app-tier
    depends_on:
      - mongodb

  # Scrappers

  marathon:
    build: ./scrappers/marathon
    volumes:
      - "./scrappers/marathon:/usr/app"
      - /usr/app/node_modules
    command: [ "npm", "run", "dev"]
    networks:
      - app-tier
    depends_on:
      - mongodb
  
  pinnacle:
    build: ./scrappers/pinnacle
    volumes:
      - "./scrappers/pinnacle:/usr/app"
      - /usr/app/node_modules
    command: [ "npm", "run", "dev"]
    networks:
      - app-tier
    depends_on:
      - mongodb
  
  # 1xbet:
  #   build: ./scrappers/1xbet
  #   volumes:
  #     - "./scrappers/1xbet:/usr/app"
  #     - /usr/app/node_modules
  #   command: [ "npm", "run", "dev"]
  #   networks:
  #     - app-tier
  #   depends_on:
  #     - mongodb
  
  # End Scrappers
    
volumes:
  mongodb_data:
    driver: local
