apiVersion: apps/v1
kind: Deployment
metadata:
  name: health
spec:
  selector:
    matchLabels:
      app: health
  template:
    metadata:
      labels:
        app: health
    spec:
      containers:
        - name: health
          image: poluga:latest
          command: [yarn, workspace, "@bet/health", dev]
          env:
            - name: MONGODB_CONNECTION_URI
              value: mongodb+srv://poluga:D0TG%25Ps92T82TH!kw9ES1YIq@cluster0-diuwt.mongodb.net/test?retryWrites=true&w=majority
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
