apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - comparator.yaml
  - health.yaml
  - scraper-marathon.yaml
  - scraper-pinnacle.yaml
images:
  - name: poluga
    newTag: $IMAGE_TAG
