apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-marathon
spec:
  selector:
    matchLabels:
      app: scraper-marathon
  template:
    metadata:
      labels:
        app: scraper-marathon
    spec:
      containers:
        - name: scraper-marathon
          image: poluga:latest
          command: [yarn, workspace, "@bet/scraper-marathon", dev]
          env:
            - name: MONGODB_CONNECTION_URI
              value: mongodb+srv://poluga:D0TG%25Ps92T82TH!kw9ES1YIq@cluster0-diuwt.mongodb.net/test?retryWrites=true&w=majority
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
