apiVersion: apps/v1
kind: Deployment
metadata:
  name: comparator
spec:
  selector:
    matchLabels:
      app: comparator
  template:
    metadata:
      labels:
        app: comparator
    spec:
      containers:
        - name: comparator
          image: poluga
          command: [yarn, workspace, "@bet/comparator", dev]
          env:
            - name: TELEGRAM_OPPORTUNITY_CHAT_ID
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: TELEGRAM_OPPORTUNITY_CHAT_ID
            - name: BET_TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: BET_TELEGRAM_BOT_TOKEN
            - name: MONGODB_CONNECTION_URI
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: MONGODB_CONNECTION_URI
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
