apiVersion: apps/v1
kind: Deployment
metadata:
  name: health
spec:
  selector:
    matchLabels:
      app: health
  template:
    metadata:
      labels:
        app: health
    spec:
      containers:
        - name: health
          image: poluga
          command: [yarn, workspace, "@bet/health", dev]
          env:
            - name: MONGODB_CONNECTION_URI
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: MONGODB_CONNECTION_URI
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
