apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - comparator.yaml
  - health.yaml
  - scraper-marathon.yaml
  - scraper-pinnacle.yaml
  - scraper-bet365.yaml
configMapGenerator:
  - name: env
    literals:
      - EVENT_TIME_SPAN_HOURS=24
