apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-marathon
spec:
  selector:
    matchLabels:
      app: scraper-marathon
  template:
    metadata:
      labels:
        app: scraper-marathon
    spec:
      containers:
        - name: scraper-marathon
          image: poluga
          command: [yarn, workspace, "@bet/scraper-marathon", start]
          env:
            - name: MONGODB_CONNECTION_URI
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: MONGODB_CONNECTION_URI
            - name: EVENT_TIME_SPAN_HOURS
              valueFrom:
                configMapKeyRef:
                  key: EVENT_TIME_SPAN_HOURS
                  name: env
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
