apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-pinnacle
spec:
  selector:
    matchLabels:
      app: scraper-pinnacle
  template:
    metadata:
      labels:
        app: scraper-pinnacle
    spec:
      containers:
        - name: scraper-pinnacle
          image: poluga
          command: [yarn, workspace, "@bet/scraper-pinnacle", dev]
          env:
            - name: MONGODB_CONNECTION_URI
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: MONGODB_CONNECTION_URI
            - name: EVENT_TIME_SPAN_HOURS
              valueFrom:
                configMapKeyRef:
                  key: EVENT_TIME_SPAN_HOURS
                  name: env
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
